services:

  redis:
    image: redis:lastest
    container_name: web-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes